/* API Assets: dependency-free explorer driven entirely by assets.json. */
const ICONS = {
  folder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>',
  'folder-open':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 19V7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v2"/><path d="m4 19 2-8h15l-2 8z"/></svg>',
  image:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/></svg>',
  document:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h6"/></svg>',
  pdf:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6"/><path d="M7 16h2a2 2 0 0 0 0-4H7v6m6-6h-2v6m6-6h-2v6"/></svg>',
  video:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="5" width="13" height="14" rx="2"/><path d="m16 10 5-3v10l-5-3z"/></svg>',
  audio:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg>',
  code:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m8 9-4 3 4 3m8-6 4 3-4 3m-2-10-4 20"/></svg>',
  file:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6"/></svg>',
  search:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
  copy:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>',
  check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>',
  preview:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12z"/><circle cx="12" cy="12" r="2.5"/></svg>',
  external:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 3h7v7M10 14 21 3M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/></svg>',
  'arrow-left':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg>',
  chevron:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg>',
  close:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m18 6-12 12M6 6l12 12"/></svg>',
  grid:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>',
  list:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 6h13M8 12h13M8 18h13"/><path d="M3 6h.01M3 12h.01M3 18h.01"/></svg>',
  sun:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32 1.41 1.41M2 12h2m16 0h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>',
  moon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.5 6.5 0 0 0 21 12.8z"/></svg>',
  layers:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m12 3 9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 16l9 5 9-5"/></svg>',
  empty:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M8 14h8"/></svg>',
  error:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 8v5m0 3h.01"/></svg>'
};
/* Named aliases keep the icon vocabulary explicit while sharing one visual system. */
Object.assign(ICONS, {
  word: ICONS.document, excel: ICONS.document, powerpoint: ICONS.document,
  json: ICONS.code, xml: ICONS.code, text: ICONS.code, csv: ICONS.code,
  'arrow-right': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg>',
  download: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"/></svg>',
  menu: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
  sort: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 6h12M8 12h8M8 18h4M4 4v16m0 0-3-3m3 3 3-3"/></svg>',
  filter: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 5h18l-7 8v5l-4 2v-7z"/></svg>',
  home: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M9 21v-6h6v6"/></svg>',
  'chevron-down': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>'
});
const $ = s => document.querySelector(s);
function storedList(key){try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[];}catch{return [];}}
const state = { data:null, current:null, search:'', view:localStorage.getItem('asset-view') || 'grid', sort:'name-asc', filter:'all', lastFocus:null, page:1, perPage:12, selected:new Set(storedList('asset-selection')), favorites:new Set(storedList('asset-favorites')), config:{tags:{}} };
function setIcons(root=document){ root.querySelectorAll('[data-icon]').forEach(el => { el.innerHTML = ICONS[el.dataset.icon] || ICONS.file; }); }
function el(tag, className, text){ const node=document.createElement(tag); if(className) node.className=className; if(text !== undefined) node.textContent=text; return node; }
function icon(name){ const s=document.createElement('span'); s.className='svg-icon'; s.innerHTML=ICONS[name] || ICONS.file; return s; }
function cleanName(name){ return String(name || '').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
function extension(file){ return (file.name.split('.').pop() || '').toLowerCase(); }
function normalizedType(file){ const ext=extension(file); if(file.type) return file.type.toLowerCase(); if(['jpg','jpeg','png','gif','webp','svg'].includes(ext)) return 'image'; if(['mp4','webm','mov'].includes(ext)) return 'video'; if(['mp3','wav','ogg'].includes(ext)) return 'audio'; if(['json','xml'].includes(ext)) return ext; if(['pdf','doc','docx','xls','xlsx','ppt','pptx','txt','csv'].includes(ext)) return 'document'; return 'other'; }
function typeLabel(file){ const t=normalizedType(file); return t==='other' ? 'File' : t[0].toUpperCase()+t.slice(1); }
function iconFor(fileOrFolder){ if(!fileOrFolder.name || fileOrFolder.children) { const n=(fileOrFolder.name||'').toLowerCase(); if(/image|photo|banner/.test(n)) return 'image'; if(/video|movie/.test(n)) return 'video'; if(/audio|sound|music/.test(n)) return 'audio'; if(/document|pdf|contract/.test(n)) return 'document'; return 'folder'; } const ext=extension(fileOrFolder); if(ext==='pdf') return 'pdf'; if(['json','xml','txt','csv'].includes(ext)) return 'code'; return ({image:'image',video:'video',audio:'audio',document:'document'})[normalizedType(fileOrFolder)] || 'file'; }
function publicURL(file){ return new URL(file.path.split('/').map(encodeURIComponent).join('/'), document.baseURI).href; }
function walk(nodes, parent=[], out=[]){ (nodes||[]).forEach(folder=>{ const path=[...parent,folder]; out.push({folder,path}); walk(folder.children,path,out); }); return out; }
function isCoverFile(file){return /^(image|cover|thumbnail)\.(png|jpg|jpeg|svg|webp)$/i.test(file.name);}
function allFiles(){ const list=[]; walk(state.data.categories).forEach(({folder,path}) => (folder.files||[]).filter(file=>!isCoverFile(file)).forEach(file=>list.push({...file, folderPath:path.map(x=>x.name)}))); return list; }
function countFolder(folder){ return (folder.files||[]).filter(file=>!isCoverFile(file)).length+(folder.children||[]).reduce((n,c)=>n+countFolder(c),0); }
function categoryCover(folder){return (folder.files||[]).find(isCoverFile);}
function renderStats(){ const files=allFiles(); const count=t=>files.filter(f=>normalizedType(f)===t).length; const stats=[[walk(state.data.categories).length,'Categories'],[files.length,'Assets'],[count('image'),'Images'],[count('document'),'Documents'],[count('video'),'Videos']]; const box=$('#stats'); box.replaceChildren(...stats.map(([n,label])=>{const d=el('div','stat'); d.append(el('strong','',String(n)),el('span','',label));return d;})); }
function folderFromHash(){ const slug=decodeURIComponent(location.hash.replace(/^#\/?/,'')); if(!slug) return null; return walk(state.data.categories).find(x=>x.folder.path===slug)?.folder || null; }
function navigate(folder){ location.hash=folder ? '#/'+encodeURIComponent(folder.path) : '#/'; }
function renderBreadcrumb(folder){ const nav=$('#breadcrumbs'); nav.replaceChildren(); if(!folder){return;} const chain=walk(state.data.categories).find(x=>x.folder===folder)?.path || []; const home=el('button','crumb','Home');home.onclick=()=>navigate(null);nav.append(home); chain.forEach((f,i)=>{nav.append(icon('chevron')); const b=el('button','crumb',cleanName(f.name)); b.onclick=()=>navigate(f); nav.append(b);}); }
function section(title, count){ const h=el('div','section-heading'); h.append(el('h2','',title),el('p','',count)); return h; }
function categoryCard(folder){ const card=el('button','category-card');card.type='button'; const top=el('div','category-icon');const cover=categoryCover(folder);const source=cover?publicURL(cover):state.config.defaultCategoryCover?new URL(state.config.defaultCategoryCover,document.baseURI).href:'';if(source){const image=document.createElement('img');image.src=source;image.alt='';image.loading='lazy';image.style.objectPosition=state.config.coverPositions?.[folder.path]||'center';image.onerror=()=>top.replaceChildren(icon(iconFor(folder)));top.append(image,icon(iconFor(folder)));}else top.append(icon(iconFor(folder))); card.append(top,el('h3','',cleanName(folder.name)),el('p','',`${countFolder(folder)} ${countFolder(folder)===1?'asset':'assets'}`)); const browse=el('div','browse','Browse');browse.append(icon('chevron'));card.append(browse);card.onclick=()=>navigate(folder);return card; }
function assetCard(file){ const card=el('article','asset-card');card.dataset.path=file.path; const visual=el('div','asset-visual'); const fileType=normalizedType(file); if(fileType==='image'){const img=document.createElement('img');img.src=publicURL(file);img.alt=file.name;img.loading='lazy';img.onerror=()=>{visual.replaceChildren(icon('image'));};visual.append(img);} else visual.append(icon(iconFor(file))); const info=el('div','asset-info');const utility=el('div','asset-utility');const select=document.createElement('input');select.type='checkbox';select.checked=state.selected.has(file.path);select.setAttribute('aria-label',`Select ${file.name}`);select.onchange=()=>toggleSelection(file.path);const favorite=el('button','favorite-button',state.favorites.has(file.path)?'Saved':'Save');favorite.type='button';favorite.onclick=()=>toggleFavorite(file.path);utility.append(select,favorite);info.append(utility,el('p','file-name',file.name),el('p','file-meta',`${extension(file).toUpperCase()} · ${typeLabel(file)}${file.size ? ` · ${file.size}` : ''}`),el('p','file-path',file.path));const actions=el('div','asset-actions');const preview=el('button','button button-quiet','Preview');preview.append(icon('preview'));preview.onclick=()=>openPreview(file);const copy=el('button','button','Copy URL');copy.append(icon('copy'));copy.onclick=()=>copyText(publicURL(file),copy,'URL copied to clipboard','Copy URL');const relative=el('button','button button-quiet','Copy path');relative.append(icon('copy'));relative.onclick=()=>copyText(file.path,relative,'Relative path copied','Copy path');const download=document.createElement('a');download.className='button button-quiet';download.href=publicURL(file);download.download=file.name;download.append(document.createTextNode('Download'),icon('download'));actions.append(preview,copy,relative,download);info.append(actions);card.append(visual,info);return card; }
function matchesFilter(file){ const type=normalizedType(file); return state.filter==='all'||(state.filter==='data'&&['json','xml'].includes(type))||type===state.filter; }
function shownFiles(files){ return sortFiles(files.filter(matchesFilter)); }
function sortFiles(files){ return [...files].sort((a,b)=>state.sort==='type' ? normalizedType(a).localeCompare(normalizedType(b)) || a.name.localeCompare(b.name) : state.sort==='newest' ? new Date(b.modified||0)-new Date(a.modified||0) || a.name.localeCompare(b.name) : state.sort==='name-desc' ? b.name.localeCompare(a.name) : a.name.localeCompare(b.name)); }
function empty(title, message, error=false){ const d=el('div','empty-state');d.append(icon(error?'error':'empty'),el('h2','',title),el('p','',message));return d; }
function renderHome(){ const root=$('#content');root.replaceChildren(); const cats=state.data.categories; if(!cats.length){root.append(empty('No assets yet','Add files to your repository and push your changes. The asset library will update automatically.'));return;} root.append(section('Categories',`${cats.length} top-level categories`));const grid=el('div','category-grid');grid.append(...cats.map(categoryCard));root.append(grid);const files=shownFiles(allFiles()).slice(0,12);if(files.length){root.append(section('All assets',`${shownFiles(allFiles()).length} matching files`));const ag=el('div',`asset-grid ${state.view}`);ag.append(...files.map(assetCard));root.append(ag);} }
function renderFolder(folder){ const root=$('#content');root.replaceChildren();const children=folder.children||[], cover=categoryCover(folder), files=shownFiles((folder.files||[]).filter(file=>!isCoverFile(file)));if(cover){const notice=el('div','cover-notice');notice.append(icon('image'),el('span','',`${cover.name} is this category’s cover image.`));root.append(notice);} if(children.length){root.append(section('Subcategories',`${children.length} folders`));const grid=el('div','category-grid');grid.append(...children.map(categoryCard));root.append(grid);} if(files.length){root.append(section('Files',`${files.length} ${files.length===1?'file':'files'}`));const ag=el('div',`asset-grid ${state.view}`);ag.append(...files.map(assetCard));root.append(ag);} if(!children.length&&!files.length)root.append(empty(state.filter==='all'?'This category is empty':'No matching files','Adjust the file type filter or select All types.')); }
function renderSearch(){ const root=$('#content');root.replaceChildren();const term=state.search.toLowerCase().trim();const files=shownFiles(allFiles().filter(f=>[f.name,f.path,extension(f),...f.folderPath].join(' ').toLowerCase().includes(term)));root.append(section(`Search results for “${state.search}”`,`${files.length} ${files.length===1?'match':'matches'}`));if(!files.length){root.append(empty('No assets found','Try a filename, file extension, category, folder name, or another type filter.'));return;}const ag=el('div',`asset-grid ${state.view}`);ag.append(...files.map(assetCard));root.append(ag); }
function render(){ state.current=folderFromHash(); const inSearch=Boolean(state.search);$('#toolbar').hidden=false;$('#backButton').hidden=!state.current;renderBreadcrumb(state.current); if(inSearch)renderSearch(); else if(state.current)renderFolder(state.current); else renderHome(); document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('is-active',b.dataset.view===state.view)); }
async function copyText(value, button, success, label){ try { if(navigator.clipboard?.writeText) await navigator.clipboard.writeText(value); else {const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();document.execCommand('copy');area.remove();} if(button){const old=button.firstChild?.textContent;button.firstChild.textContent='Copied';button.replaceChild(icon('check'),button.lastChild);setTimeout(()=>{button.firstChild.textContent=old||label;button.replaceChild(icon('copy'),button.lastChild);},1600);}showToast(success);}catch{showToast('Unable to copy');} }
function showToast(message){const t=$('#toast');t.replaceChildren(icon('check'),document.createTextNode(message));t.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.hidden=true,2600);}
function detailList(file, url){ const details=el('div','preview-details');const rows=[['Type',typeLabel(file)],['Extension',extension(file).toUpperCase()],['Folder',file.path.split('/').slice(0,-1).join('/')||'Root'],['Size',file.size],['Dimensions',file.dimensions],['Duration',file.duration],['Modified',file.modified ? new Date(file.modified).toLocaleDateString() : ''],['URL',url]].filter(([,value])=>value);rows.forEach(([a,b])=>{const row=el('div','detail-row');row.append(el('span','',a),a==='URL'?el('code','',b):el('strong','',b));details.append(row);});return details;}
async function openPreview(file){ const modal=$('#modal'),body=$('#modalBody'),title=$('#modalTitle'),url=publicURL(file),type=normalizedType(file);state.lastFocus=document.activeElement;title.textContent=file.name;body.replaceChildren(); if(type==='image'){const image=document.createElement('img');image.src=url;image.alt=file.name;body.append(image,detailList(file,url));}else if(type==='video'){const v=document.createElement('video');v.src=url;v.controls=true;v.autoplay=true;body.append(v,detailList(file,url));}else if(type==='audio'){const a=document.createElement('audio');a.src=url;a.controls=true;a.autoplay=true;body.append(a,detailList(file,url));}else if(extension(file)==='pdf'){const frame=document.createElement('iframe');frame.src=url;frame.title=file.name;frame.width='100%';frame.height='560';body.append(frame,detailList(file,url));}else if(['json','xml','txt','csv'].includes(extension(file))){const pre=el('pre','code-preview','Loading preview…');body.append(pre,detailList(file,url));try{const text=await fetch(url).then(r=>r.ok?r.text():Promise.reject());if(extension(file)==='json'){try{pre.textContent=JSON.stringify(JSON.parse(text),null,2);}catch{pre.textContent=text;}}else pre.textContent=text;}catch{pre.textContent='This file could not be loaded for preview.';}}else{const details=detailList(file,url);const open=el('a','button','Open file');open.href=url;open.target='_blank';open.rel='noopener';open.append(icon('external'));details.append(open);body.append(details);}modal.hidden=false;$('#modalClose').focus(); }
function closeModal(){ const modal=$('#modal'); if(modal.hidden)return;modal.hidden=true;$('#modalBody').replaceChildren();state.lastFocus?.focus(); }
function persistSets(){localStorage.setItem('asset-selection',JSON.stringify([...state.selected]));localStorage.setItem('asset-favorites',JSON.stringify([...state.favorites]));}
function toggleSelection(path){state.selected.has(path)?state.selected.delete(path):state.selected.add(path);persistSets();updateSelectionBar();}
function toggleFavorite(path){state.favorites.has(path)?state.favorites.delete(path):state.favorites.add(path);persistSets();render();}
function updateSelectionBar(){const bar=$('#selectionBar');bar.hidden=!state.selected.size;$('#selectionCount').textContent=`${state.selected.size} selected`;}
function renderTree(){const root=$('#folderTree');root.replaceChildren();const add=(folders,depth=0)=>folders.forEach(folder=>{const b=el('button','tree-node',cleanName(folder.name));b.style.paddingLeft=`${12+depth*16}px`;b.onclick=()=>navigate(folder);root.append(b);add(folder.children||[],depth+1);});add(state.data.categories);}
function copyPostman(file){copyText(JSON.stringify({assetUrl:publicURL(file)},null,2),null,'Postman JSON copied','');}
function loadConfig(){return fetch('./library-config.json').then(r=>r.ok?r.json():{}).catch(()=>({}));}
async function init(){ setIcons(); const saved=localStorage.getItem('asset-theme'); if(saved)document.documentElement.dataset.theme=saved; $('#themeToggle').innerHTML=ICONS[document.documentElement.dataset.theme==='dark'?'sun':'moon']; try{const res=await fetch('./assets.json',{cache:'no-store'});if(!res.ok)throw Error();state.data=await res.json();}catch{state.data=window.ASSET_INDEX;}state.config=await loadConfig();if(state.config.title){document.title=`${state.config.title} — Asset Library`;document.querySelector('.brand strong').textContent=state.config.title;}if(state.config.subtitle)document.querySelector('.brand small').textContent=state.config.subtitle;if(state.config.accentColor)document.documentElement.style.setProperty('--brand',state.config.accentColor);if(Array.isArray(state.data?.categories)){renderStats();renderTree();render();updateSelectionBar();return;}const expected=new URL('assets.json',document.baseURI).href;$('#content').replaceChildren(empty('Unable to load asset library',`The asset index was not found at ${expected}. Make sure assets.json and assets-data.js are beside index.html, or open the deployed GitHub Pages URL.`,true));}
$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;render();});$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Escape'){e.currentTarget.value='';state.search='';render();}});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus();}if(e.key==='Escape')closeModal();if(e.key==='Tab'&&!$('#modal').hidden){const focusable=$('#modal').querySelectorAll('button,a[href],video[controls],audio[controls]');const list=[...focusable];if(!list.length)return;const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});$('#themeToggle').onclick=()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==='dark'?'light':'dark';localStorage.setItem('asset-theme',d.dataset.theme);$('#themeToggle').innerHTML=ICONS[d.dataset.theme==='dark'?'sun':'moon'];};$('#backButton').onclick=()=>history.back();$('#sortSelect').onchange=e=>{state.sort=e.target.value;render();};$('#typeFilter').onchange=e=>{state.filter=e.target.value;render();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;localStorage.setItem('asset-view',state.view);render();});$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};window.addEventListener('hashchange',render);init();
